name: Deploy Node.js to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd "redbus project"
          npm install

      - name: Check Syntax Error
        run: |
          cd "redbus project"
          node --check redbus.js
          npx eslint .
          npm test 

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/RedBus-APi-AWS-EC2-
            git pull origin main
            cd "redbus project"
            npm install
            pm2 restart redbus-api || pm2 start redbus.js --name "redbus-api"